---
- name: Deploy Nginx with a random page
  hosts: web_servers
  become: yes
  tasks:
    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Create index.html with random content
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        content: "Benvenuto, goblin {{ 100 + ansible_date_time.epoch | int % 100 }}!"
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Ensure Nginx is running
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
